### DISCUSSION TITLE
How to setup a egree to azure blob

### DISCUSSION THREAD

**Discussion by mrhovunping** [dotnet/dotnet-monitor#2263] [Q&A] [answered]
Hi team,

 I'd like to test dotnet-monitor to publish gcdump on azure.

1 - I have setup a azure blog storage with a container
2 - Run test app on kube using manifest

``` 
apiVersion: v1
metadata:
  name: monitor-environment-configuration
kind: ConfigMap
data: 
  Egress__AzureBlobStorage__monitorBlob__accountUri: "https://storagesamplesequativ.blob.core.windows.net"
  Egress__AzureBlobStorage__monitorBlob__containerName: "dotnet-monitor"
  Egress__AzureBlobStorage__monitorBlob__blobPrefix: "artifacts"
  Egress__AzureBlobStorage__monitorBlob__accountKeyName: "accountKey"
  Egress__Properties__accountKey: "**********"
  
  DiagnosticPort: "/diag/port.sock"

  DiagnosticPort__ConnectionMode: "Listen"
  DiagnosticPort__EndpointName: "/diag/port.sock"
  Storage__DumpTempFolder: "/diag/dumps"

  # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
  # demonstration purposes only in this example. Please continue reading after this example for further details.
  Urls: "http://*:52323"

---

apiVersion: v1
data: 
  #eyffffffffffffFsRGF0YSI6e30sIkNydiI6IlAtMzg0IiwiS2V5T3BzIjpbXSwiS3R5IjoiRUMiLCJYIjoiTnhIRnhVZ19QM1dhVUZWVzk0U3dUY3FzVk5zNlFLYjZxc3AzNzVTRmJfQ3QyZHdpN0RWRl8tUTVheERtYlJuWSIsIlg1YyI6W10sIlkiOiJmMXBDdmNoUkVpTWEtc1h6SlZQaS02YmViMHdrZmxfdUZBN0Vka2dwcjF5N251Wmk2cy1NcHl5RzhKdVFSNWZOIiwiS2V5U2l6ZSI6Mzg0LCJIYXNQcml2YXRlS2V5IjpmYWxzZSwiQ3J5cHRvUHJvdmlkZXJGYWN0b3J5Ijp7IkNyeXB0b1Byb3ZpZGVyQ2FjaGUiOnt9LCJDYWNoZVNpZ25hdHVyZVByb3ZpZGVycyI6dHJ1ZSwiU2lnbmF0dXJlUHJvdmlkZXJPYmplY3RQb29sQ2FjaGffffffffffff19
  Authentication__MonitorApiKey__PublicKey: ZXlmZmZmZmZmZmZmZmZGc1JHRjBZU0k2ZTMwc0lrTnlkaUk2SWxBdE16ZzBJaXdpUzJWNVQzQnpJanBiWFN3aVMzUjVJam9pUlVNaUxDSllJam9pVG5oSVJuaFZaMTlRTTFkaFZVWldWemswVTNkVVkzRnpWazV6TmxGTFlqWnhjM0F6TnpWVFJtSmZRM1F5WkhkcE4wUldSbDh0VVRWaGVFUnRZbEp1V1NJc0lsZzFZeUk2VzEwc0lsa2lPaUptTVhCRGRtTm9Va1ZwVFdFdGMxaDZTbFpRYVMwMlltVmlNSGRyWm14ZmRVWkJOMFZrYTJkd2NqRjVOMjUxV21rMmN5MU5jSGw1UnpoS2RWRlNOV1pPSWl3aVMyVjVVMmw2WlNJNk16ZzBMQ0pJWVhOUWNtbDJZWFJsUzJWNUlqcG1ZV3h6WlN3aVEzSjVjSFJ2VUhKdmRtbGtaWEpHWVdOMGIzSjVJanA3SWtOeWVYQjBiMUJ5YjNacFpHVnlRMkZqYUdVaU9udDlMQ0pEWVdOb1pWTnBaMjVoZEhWeVpWQnliM1pwWkdWeWN5STZkSEoxWlN3aVUybG5ibUYwZFhKbFVISnZkbWxrWlhKUFltcGxZM1JRYjI5c1EyRmphR2ZmZmZmZmZmZmZmZjE5
  #ae5473b6-8dad-498d-b915-ffffffffffff
  Authentication__MonitorApiKey__Subject: YWU1NDczYjYtOGRhZC00OThkLWI5MTUtZmZmZmZmZmZmZmZm
kind: Secret
metadata:
  name: apikey

---
# Tell us about your experience using dotnet monitor: https://aka.ms/dotnet-monitor-survey
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "52325"
    spec:
      restartPolicy: Always
      containers:
      - name: app1
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/port.sock
        volumeMounts:
        - name: diagvol
          mountPath: /diag
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor
        args: [ "--no-auth" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 52325
          name: metrics
        volumeMounts:
        - name: diagvol
          mountPath: /diag
        - name: config
          mountPath: /etc/dotnet-monitor
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: diagvol
        emptyDir: {}
      - name: config
        projected:
          sources:
            - secret:
                name: apikey
            - configMap:
                name: monitor-environment-configuration
---

apiVersion: v1
kind: Service
metadata:
  name: exampleapp-service
  namespace: default
  labels:
    app: exampleapp-service
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: exampleapp
  type: NodePort
```

3 - I'll do a port-forward to access the api
4 - open a browser and run  `http://[localhost:8080/gcdump?egressProvider=monitorBlob](http://localhost:8080/gcdump?egressProvider=monitorBlob)`

I get the following:
![image](https://user-images.githubusercontent.com/10894068/183107224-2e093a4d-7244-429d-91d4-e965112ecd28.png)

I am sure it is a problem with configuration, can you help me?
