### DISCUSSION TITLE
AKS : Sidecar dotnet-monitor container is throwing error 400 - Unable to discover the target process

### DISCUSSION THREAD

**Discussion by vaibhav-shimpi-maersk** [dotnet/dotnet-monitor#4815] [General]
There is a lot of memory consumption issue occurring in Production. To analyse the pod - dotnet application memory and its usage, we would like to collect the managed memory and GCDUMP. For this reason, we have implemented the sidecar pattern to install the dotnet-monitor tool in one container and track the main container within same pod.
The approach is implemented and tested using minikube and is working fine in local environment. I am not sure what is blocking not to collect the processes, dump and gcdump in AKS. 
Following is the deployment.yaml file -
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-monitor-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-monitor-k8s
  template:
    metadata:
      labels:
        app: dotnet-monitor-k8s
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 952
        runAsGroup: 952
        runAsNonRoot: true
        fsGroup: 952
      volumes:
      - name: diagnostics
        emptyDir: {}
      - name: tools
        emptyDir: {}
      containers:
      - name: dotnet-monitor-k8s
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/port.sock
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /diag
            name: diagnostics
          - mountPath: /tools/data
            name: tools
        resources:
          requests:
            cpu: "100m"
            memory: 256Mi
          limits:
            cpu: "400m"
            memory: 512Mi
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:6-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 52323
        args: ["--urls", "http://*:52323", "--no-auth"]
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: 'Listen'
        - name: DOTNETMONITOR_DiagnosticPort__EndpointName
          value: /diag/port.sock
        # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
        # demonstration purposes only in this example. Please continue reading after this example for further details.
        - name: DOTNETMONITOR_Urls
          value: 'http://localhost:52323'
        - name: DOTNETMONITOR_Storage__DumpTempFolder
          value: /diag/dumps
        - name: DOTNETMONITOR_Logging__Console__FormatterName
          value: simple
        volumeMounts:
          - name: diagnostics
            mountPath: /diag
          - mountPath: /tools/data
            name: tools
        resources:
          requests:
            cpu: "100m"
            memory: 256Mi
          limits:
            cpu: "400m"
            memory: 512Mi
-----------------------
INGRESS YAML 

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dotnet-monitor-k8s-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: k8s.dotnet-monitor.com #for local development, update the /etc/hosts 127.0.0.1 alias to it (for macos)
    http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: dotnet-monitor-k8s-external
            port:
              number: 80

---------
SERVICE YAML
apiVersion: v1
kind: Service
metadata:
  name: dotnet-monitor-k8s-external
spec:
  type: LoadBalancer
  selector:
    app: dotnet-monitor-k8s
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 52325
    targetPort: 52325
```
After applying the above yaml file, the steps carried out are as follows -

1. Kubectl get pods -n gco-dev
	
2. Check logs of respective pods whether both containers are running fine
	a. kubectl logs
	b. kubectl logs monitor
	
3. Login to application container to check whether the processes are running -
	a. kubectl exec -it -- sh
	b. ps aux
	c. netstat -tulpnx
	d. exit
	This is ensuring the dotnet application is running with process ID and also diagnostics sockets are listening.
	
4. Login to side care monitor container to check whether processes are running -
	a. kubectl exec -it -c monitor -- sh
	b. ps aux
	c. netstat -tulpnx
	d. exit
	This is ensuring the dotnet-monitor tool is running with process ID and also diagnostics sockets are listening.
	
5. kubectl port-forward pods/ 7000:52323
	
6. Navigate to http://localhost:7000/info. This will show the following output -
	{"version":"6.3.2+68aa7e8f1d65aa702a75525176bb72f2b50c1bba","runtimeVersion":"6.0.19","diagnosticPortMode":"Listen","diagnosticPortName":"/diag/port.sock"}
	
7.Navigate to http://localhost:7000/processes. This is showing the blank array in AKS-
	[]
	In minikube, it is displaying - [{"pid":1,"uid":"d1a6f3d5-b420-43b3-9690-111801eadf78","name":"aspnetapp","isDefault":true}]
	
8. Navigate to http://localhost:7000/dump. This is giving error in AKS -
400 - unable to discover a target process
In minikube, it is downloading the dump file.

I have also tried with removing the securityContext and running the pods on root user, same non-root user number but no luck

I also tried to collect the dump by logging into monitor container and executing - dotnet-monitor collect -u http://localhost:52323 or some other port, it is giving the expection http://localhost:52323 is already is in use
