### DISCUSSION TITLE
Potential performance issue with exception monitoring in .NET Monitor 8.0.0

### DISCUSSION THREAD

**Discussion by schmittjoseph** [dotnet/dotnet-monitor#5747] [Announcements]
We've recently become aware that **if** `InProcessFeatures` is enabled in .NET Monitor 8.0.0, then the default configuration may lead to potential performance issues in monitored applications in certain scenarios.

> [!IMPORTANT]
> `InProcessFeatures` is **not** enabled by default in 8.0.0 so this issue only applies if it has been manually enabled.

For customers using 8.0.0 with `InProcessFeatures` enabled, you can mitigate this potential issue by toggling the `DOTNETMONITOR_InProcessFeatures__Exceptions__Enabled` configuration property to `false`.

<details>
  <summary>JSON Configuration</summary>

```json
{
  "InProcessFeatures": {
    "Enabled": true,
    "Exceptions": {
      "Enabled": false
    }
  }
}
```

</details>

<details>
  <summary>Kubernetes Environment Variables</summary>

```yaml
- name: DOTNETMONITOR_InProcessFeatures__Enabled
  value: "true"
- name: DOTNETMONITOR_InProcessFeatures__Exceptions__Enabled
  value: "false"
```

</details>
