### ISSUE TITLE
"Unable to discover a target process" when using with kubernetes

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-monitor#1236]
## Description

When I try to use dotnet-monitor as a sidecar, I could not get my dotnet application info from dotnet-monitor, when I try to access the `logs`/`livemetrics`/..., I would get a 400 returned like follows:

![](https://user-images.githubusercontent.com/7604648/147193520-28659175-865e-4bdb-bb62-0221496bbda2.png)

My Kubernetes yaml config is as follows, source file: <https://github.com/WeihanLi/SparkTodo/blob/master/sparktodo-api-k8s-deploy.yaml>

``` yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparktodo-api
  labels:
    app: sparktodo-api
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: sparktodo-api
  minReadySeconds: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "52323"
      labels: 
        app: sparktodo-api
    
    spec:
      containers:
        - name: sparktodo-api
          image: weihanli/sparktodo-api:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 30
          volumeMounts:
          - mountPath: /diag
            name: diagvol
          - mountPath: /dumps
            name: dumpsvol
        - name: monitor
          image: mcr.microsoft.com/dotnet/monitor:6.0.0
          # DO NOT use the --no-auth argument for deployments in production
          args: [ "--no-auth" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 52323
          env:
          - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
            value: Listen
          - name: DOTNETMONITOR_DiagnosticPort__EndpointName
            value: /diag/port
          - name: DOTNETMONITOR_Storage__DumpTempFolder
            value: /dumps
          - name: DOTNETMONITOR_Urls
            value: "http://*:52323"
          volumeMounts:
          - mountPath: /diag
            name: diagvol
          - mountPath: /dumps
            name: dumpsvol
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 256Mi
          securityContext:
            capabilities:
              add: ["SYS_PTRACE"]
      volumes:
      - name: diagvol
        emptyDir: {}
      - name: dumpsvol
        emptyDir: {}
```

### Other information

Error logs from container:

```
{"Timestamp":"2021-12-23T05:40:58.1246150Z","EventId":1,"LogLevel":"Error","Category":"Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController","Message":"Request failed.","Exception":"System.ArgumentException: Unable to discover a target process.    at Microsoft.Diagnostics.Monitoring.WebApi.DiagnosticServices.GetProcessAsync(DiagProcessFilter processFilterConfig, CancellationToken token) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs:line 100    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.\u003C\u003Ec__DisplayClass32_0\u00601.\u003C\u003CInvokeForProcess\u003Eb__0\u003Ed.MoveNext() in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs:line 687 --- End of stack trace from previous location ---    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagControllerExtensions.InvokeService[T](ControllerBase controller, Func\u00601 serviceCall, ILogger logger) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagControllerExtensions.cs:line 57","State":{"Message":"Request failed.","{OriginalFormat}":"Request failed."},"Scopes":[{"Message":"SpanId:65cb0d7101891a70, TraceId:31ff86de0f44193cb3fdedd60987475a, ParentId:0000000000000000","SpanId":"65cb0d7101891a70","TraceId":"31ff86de0f44193cb3fdedd60987475a","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HME5QNE1NAGE","ConnectionId":"0HME5QNE1NAGE"},{"Message":"RequestPath:/livemetrics RequestId:0HME5QNE1NAGE:00000003","RequestId":"0HME5QNE1NAGE:00000003","RequestPath":"/livemetrics"},{"Message":"Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureMetrics (Microsoft.Diagnostics.Monitoring.WebApi)","ActionId":"3ace608d-d0da-4d60-b768-70dcd3e2d3ef","ActionName":"Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureMetrics (Microsoft.Diagnostics.Monitoring.WebApi)"},{"Message":"ArtifactType:livemetrics","ArtifactType":"livemetrics"}]}
{"Timestamp":"2021-12-23T05:40:58.7240492Z","EventId":1,"LogLevel":"Error","Category":"Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController","Message":"Request failed.","Exception":"System.ArgumentException: Unable to discover a target process.    at Microsoft.Diagnostics.Monitoring.WebApi.DiagnosticServices.GetProcessAsync(DiagProcessFilter processFilterConfig, CancellationToken token) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/DiagnosticServices.cs:line 100    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.\u003C\u003Ec__DisplayClass32_0\u00601.\u003C\u003CInvokeForProcess\u003Eb__0\u003Ed.MoveNext() in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagController.cs:line 687 --- End of stack trace from previous location ---    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagControllerExtensions.InvokeService[T](ControllerBase controller, Func\u00601 serviceCall, ILogger logger) in /_/src/Microsoft.Diagnostics.Monitoring.WebApi/Controllers/DiagControllerExtensions.cs:line 57","State":{"Message":"Request failed.","{OriginalFormat}":"Request failed."},"Scopes":[{"Message":"SpanId:319035d77c7f0686, TraceId:84fc86957c67486c92a2838b98241f3b, ParentId:0000000000000000","SpanId":"319035d77c7f0686","TraceId":"84fc86957c67486c92a2838b98241f3b","ParentId":"0000000000000000"},{"Message":"ConnectionId:0HME5QNE1NAGE","ConnectionId":"0HME5QNE1NAGE"},{"Message":"RequestPath:/livemetrics RequestId:0HME5QNE1NAGE:00000004","RequestId":"0HME5QNE1NAGE:00000004","RequestPath":"/livemetrics"},{"Message":"Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureMetrics (Microsoft.Diagnostics.Monitoring.WebApi)","ActionId":"3ace608d-d0da-4d60-b768-70dcd3e2d3ef","ActionName":"Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureMetrics (Microsoft.Diagnostics.Monitoring.WebApi)"},{"Message":"ArtifactType:livemetrics","ArtifactType":"livemetrics"}]}
```
