### ISSUE TITLE
Duplicate records cause prometheus to complain

### ISSUE THREAD

**Issue by silencej** [dotnet/dotnet-monitor#13]
Problem: After deployment in Docker environment, the prometheus scraper complains errors like:
```
Error on ingesting out-of-order samples
Error on ingesting samples with different value but same timestamp
```

`curl 127.0.0.1:52323/metrics` shows that there are duplicate records like:

```
$ curl 127.0.0.1:52323/metrics
# HELP systemruntime_cpu_usage_ratio CPU Usage
# TYPE systemruntime_cpu_usage_ratio gauge
systemruntime_cpu_usage_ratio 2 1599789718453
systemruntime_cpu_usage_ratio 2 1599789728453
systemruntime_cpu_usage_ratio 2 1599789738453
# HELP systemruntime_working_set_bytes Working Set
# TYPE systemruntime_working_set_bytes gauge
systemruntime_working_set_bytes 1017000000 1599789708454
systemruntime_working_set_bytes 1017000000 1599789718454
systemruntime_working_set_bytes 1017000000 1599789728456
# HELP systemruntime_gc_heap_size_bytes GC Heap Size
# TYPE systemruntime_gc_heap_size_bytes gauge
systemruntime_gc_heap_size_bytes 756000000 1599789708454
systemruntime_gc_heap_size_bytes 756000000 1599789718454
systemruntime_gc_heap_size_bytes 756000000 1599789728457
# HELP systemruntime_gen_0_gc_count Gen 0 GC Count
# TYPE systemruntime_gen_0_gc_count gauge
systemruntime_gen_0_gc_count 2 1599789708454
systemruntime_gen_0_gc_count 2 1599789718454
systemruntime_gen_0_gc_count 2 1599789728457
# HELP systemruntime_gen_1_gc_count Gen 1 GC Count
# TYPE systemruntime_gen_1_gc_count gauge
systemruntime_gen_1_gc_count 0 1599789708454
systemruntime_gen_1_gc_count 0 1599789718454
systemruntime_gen_1_gc_count 0 1599789728457
# HELP systemruntime_gen_2_gc_count Gen 2 GC Count
# TYPE systemruntime_gen_2_gc_count gauge
systemruntime_gen_2_gc_count 0 1599789708454
systemruntime_gen_2_gc_count 0 1599789718454
systemruntime_gen_2_gc_count 0 1599789728457
```

Why there are the duplicate metrics with different values?

My configuration is:

```yaml
  webapi:
    volumes:
    - dotnet_monitor_data:/tmp

  dnm:
    image: mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.2-alpine
    volumes:
    - dotnet_monitor_data:/tmp
    ports:
    - 52323:52323
    command: --urls http://*:52323
```

Prometheus config

```yaml
  - job_name: 'dotnet-mon'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.1:52323'] # The IP is the host IP, accessed by the prometheus docker.
```
