### ISSUE TITLE
Can't get a CollectionRule to trigger

### ISSUE THREAD

**Issue by joelnotified** [dotnet/dotnet-monitor#1734]
I'm trying to setup a simple CollectionRule, but I can't get it to work, so I'm not sure that I've configured it correctly?

I've based it on [this example](https://github.com/mjrousos/DotNetDiagnosticsSamples/blob/main/5-Deadlock/k8s.yaml), and here's what I have:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scenario5
  selfLink: /api/v1/namespaces/default/pods/scenario5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scenario5
      component: webapi
  template:
    metadata:
      labels:
        app: scenario5
        component: webapi
    spec:
      volumes:
        - name: diagnostics
          emptyDir: {}
        - name: dotnet-monitor-config
          configMap:
            name: dotnet-monitor-config
      containers:
        - name: testapp
          image: mjrousos/diagnostics-scenario5:1.4
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /tmp
              name: diagnostics
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
        - name: sidecar
          image: mcr.microsoft.com/dotnet/monitor:6.1.0
          ports:
            - containerPort: 52323
          args: ["--urls", "http://*:52323", "--no-auth"]
          volumeMounts:
            - name: diagnostics
              mountPath: /tmp
            - name: dotnet-monitor-config
              mountPath: /etc/dotnet-monitor
          resources:
            limits:
              memory: 1Gi
              cpu: "0.5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-monitor-config
data:
  Egress__FileSystem__artifacts__directoryPath: "/artifacts"
  CollectionRules__HighCpuUsage__Trigger__Type: "Startup"
  CollectionRules__HighCpuUsage__Actions__0__Type: "CollectTrace"
  CollectionRules__HighCpuUsage__Actions__0__Settings__Profile: "Cpu"
  CollectionRules__HighCpuUsage__Actions__0__Settings__Duration: "00:00:05"
  CollectionRules__HighCpuUsage__Actions__0__Settings__Egress: "artifacts"
```

I would a assume that a Cpu trace would be triggered on startup, run for 5 seconds, and then be outputted to a directory called artifacts in the dotnet-monitor container. What am I doing wrong? 🤔
