### ISSUE TITLE
/dump fails with "WriteDumpAsync failed - HRESULT: 0x00000000"

### ISSUE THREAD

**Issue by plaisted** [dotnet/dotnet-monitor#1783]
### Description

When attempting to take a full dump by navigating to /dump endpoint (with defaults) the following error message is returned:
```json
{"status":400,"detail":"WriteDumpAsync failed - HRESULT: 0x00000000"}
```

Only mention I see of this error is in #1216 but I've verified folder exists and is writable:
```yaml
# on sidecar
            - name: DOTNETMONITOR_Storage__DumpTempFolder
              value: /dumps
# on both sidecar and app
            - mountPath: /dumps
              name: dumpsvol
```

### Configuration

Pod with process running RHEL UBI8 (registry.access.redhat.com/ubi8/dotnet-60-runtime:6.0-5)
```
Dotnet --info
  Version: 6.0.2
  Commit:  839cdfb0ec
```

Sidecar (ms provided container)
/info:
```json
{"version":"6.1.1+17a566bc3228b2ea2a9bfa6d75423637c340943a","runtimeVersion":"6.0.4","diagnosticPortMode":"Connect","diagnosticPortName":null}
```
Configured with defaults other than "--no-auth" arg and DOTNETMONITOR_Urls and DOTNETMONITOR_Storage__DumpTempFolder env vars set.

### Other information

* /trace & /gcdump work without issue.
* I've tried adding SYS_PTRACE capability to both and shareProcessNamespace as well since I saw those mentioned occasionally but same error occurred. I think those were for older dotnet dump versions anyway.
