### ISSUE TITLE
Dotnet monitor showing target processes as empty when running in Azure Kubernetes Cluster

### ISSUE THREAD

**Issue by mbhaska6** [dotnet/dotnet-monitor#2327]
I am working with .Net Monitor tool to profiling and debug my Microservices in development environment to find out the CPU, memory usage, memory leaks and diagnose slowness of application in runtime. 

In this context, I have able to deploy the dotnet-monitor as a sidecar container along with my primary application container. I can see both containers are running successfully and can able to see the /info api( http://localhost:52323/info) endpoint status in both connect and listen mode.  But when I triggered the any other API of .NET monitor like (http://localhost:52323/processes, http://localhost:52323/trace, and  http://localhost:52323/logs) showing status message "Unable to discover a target process" with status code as 400.

I have tried with following configurations (both connect and Listen mode)

Config 1:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enlp-filtertext-service-cluster2
  labels:
    helm.sh/chart: enlp-filtertext-service-0.1.0
    app.kubernetes.io/name: enlp-filtertext-service
    app.kubernetes.io/instance: enlp-filtertext-service-cluster2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: enlp-filtertext-service
      app.kubernetes.io/instance: enlp-filtertext-service-cluster2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enlp-filtertext-service
        app.kubernetes.io/instance: enlp-filtertext-service-cluster2
    spec:
      imagePullSecrets:
        - name: enlpcontainerregistrymain-secret
      serviceAccountName: enlp-filtertext-service-cluster2
      securityContext:
        {}
      containers:
        - name: enlp-filtertext-service
          securityContext:
            {}
          image: "enlpcontainerregistrymain.azurecr.io/enlp-filtertext-service:9.1.206"
          imagePullPolicy: Always
          env:
          - name: DotnetMonitor_DiagnosticPort
            value: /temp/port.sock
          volumeMounts:
           - mountPath: /temp
             name: dotnet-monitor
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          envFrom:
          - configMapRef:
              name: enlp-filtertext-service-cluster2-configmap
          resources:
            {}
        - name: dotnet-monitor
          image: mcr.microsoft.com/dotnet/monitor:6.0.0
          imagePullPolicy: Always
          env:
          - name: DotnetMonitor_DiagnosticPort__ConnectionMode
            value: "Listen"
          - name: DotnetMonitor_DiagnosticPort__EndpointName
            value: "/temp/port.sock"
          ports:
          - containerPort: 52323
          args: ["--urls", "http://*:52323", "--no-auth" ]
          volumeMounts:
           - mountPath: /temp
             name: dotnet-monitor
          resources:
           requests:
             cpu: 50m
             memory: 32Mi
           limits:
             cpu: 250m
             memory: 256Mi
      volumes:
       - name: dotnet-monitor
         emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
```

==================================
Config 2:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enlp-filtertext-service-cluster2
  labels:
    helm.sh/chart: enlp-filtertext-service-0.1.0
    app.kubernetes.io/name: enlp-filtertext-service
    app.kubernetes.io/instance: enlp-filtertext-service-cluster2
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: enlp-filtertext-service
      app.kubernetes.io/instance: enlp-filtertext-service-cluster2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: enlp-filtertext-service
        app.kubernetes.io/instance: enlp-filtertext-service-cluster2
    spec:
      imagePullSecrets:
        - name: enlpcontainerregistrymain-secret
      serviceAccountName: enlp-filtertext-service-cluster2
      securityContext:
        {}
      containers:
        - name: enlp-filtertext-service
          securityContext:
            {}
          image: "enlpcontainerregistrymain.azurecr.io/enlp-filtertext-service:9.1.206"
          imagePullPolicy: Always
          volumeMounts:
           - mountPath: /temp
             name: dotnet-monitor
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
          envFrom:
          - configMapRef:
              name: enlp-filtertext-service-cluster2-configmap
          resources:
            {}
        - name: dotnet-monitor
          image: mcr.microsoft.com/dotnet/monitor:6.0.0
          imagePullPolicy: Always
          ports:
          - containerPort: 52323
          args: ["--urls", "http://*:52323", "--no-auth" ]
          volumeMounts:
           - mountPath: /temp
             name: dotnet-monitor
          resources:
           requests:
             cpu: 50m
             memory: 32Mi
           limits:
             cpu: 250m
             memory: 256Mi
      volumes:
       - name: dotnet-monitor
         emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
```

![scrn1](https://user-images.githubusercontent.com/111407823/185036331-62749806-16e7-4e27-9735-8f8ad1044804.png)

![scrn2](https://user-images.githubusercontent.com/111407823/185036927-b75ef9f7-5b14-46b0-9574-96855bae9bd7.png)
