### ISSUE TITLE
The runtime has been configured to pause during startup

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#2487]
@jander-msft I have the same issue, I can verify all those three steps.

![image](https://user-images.githubusercontent.com/22220356/189959403-30f2c95b-1b5f-4480-876f-38fb1173fc00.png)

1. There is a dotnet monitor container
![image](https://user-images.githubusercontent.com/22220356/189957981-a0253dcb-7c5b-4b5e-915f-5e69fc3393fe.png)

2. It is configured to host its diagnostic port at /diag/port

#### app contrainer envs:

```
- name: DOTNET_DiagnosticPorts
  value: /diag/port.sock
```

#### dotnet monitor contrainer 

```
- name: monitor
  image: mcr.microsoft.com/dotnet/monitor:6-alpine
  args: [ "--no-auth" ]
  imagePullPolicy: IfNotPresent
  ports:
    - name: metrics
      containerPort: 52323
  env:
    - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
      value: "Listen"
    - name: DOTNETMONITOR_DiagnosticPort__EndpointName
      value: "/diag/port.sock"
    - name: DOTNETMONITOR_Storage__DumpTempFolder
      value: "/diag/dumps"
    - name: DOTNETMONITOR_Urls
      value: http://+:52323
    - name: DotnetMonitor_Logging__LogLevel__Microsoft
      value: Trace
    - name: DOTNETMONITOR_Logging__LogLevel__Default
      value: Trace
    - name: DotnetMonitor_Logging__LogLevel__Microsoft__Diagnostics
      value: Trace
  volumeMounts:
    - mountPath: /diag
      name: diagvol
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "256Mi"
      cpu: "250m"   
```

3. The /diag folder is mounted to the same volume between the application container and the dotnet monitor container.

#### app contrainer:

![image](https://user-images.githubusercontent.com/22220356/189958818-49f7c9c2-599d-4373-94d0-197a4c034a7e.png)

#### dotnet-monitor container:

![image](https://user-images.githubusercontent.com/22220356/189959079-09cf7879-9d32-4499-80d8-5ed91c33f253.png)

There is nothing special in dotnet monitor logs

_Originally posted by @xsoheilalizadeh in https://github.com/dotnet/dotnet-monitor/issues/1958#issuecomment-1245676353_
