### ISSUE TITLE
 Unrecognized command or argument '--no-auth' in 7.0

### ISSUE THREAD

**Issue by xsoheilalizadeh** [dotnet/dotnet-monitor#2892]
I used the current Kubernetes documentation and it's passing '--no-auth' argument when the container starts, in version 6 it was working fine but in version 7 it's broken.

How can I set --no-auth in the new version?

```
 Unrecognized command or argument '--no-auth'.
```

```
- name: monitor
  securityContext:
    runAsUser: 1000
  image: mcr.microsoft.com/dotnet/monitor
  args: [ "--no-auth" ]
  imagePullPolicy: IfNotPresent
  ports:
    - name: metrics
      containerPort: 9100
```
