### ISSUE TITLE
execve(./createdump) FAILED No such file or directory

### ISSUE THREAD

**Issue by gest01** [dotnet/dotnet-monitor#2932]
### Description

I've setup dotnet monitor in my minikube cluster using the kubernetes example provided by this repo: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/kubernetes.md

First, i had to change the image **mcr.microsoft.com/dotnet/monitor** to **mcr.microsoft.com/dotnet/monitor:6**. Otherwise the **monitor** was not started:

```bash
k logs deploy-exampleapp-dd86f98f-k558l monitor -f

Required command was not provided.
Unrecognized command or argument '--no-auth'.
```
Anyway, as soon as i switched to **mcr.microsoft.com/dotnet/monitor:6**, the deployment with 3 containers (app1, app2 and monitor) started successfully :-)

![image](https://user-images.githubusercontent.com/564678/204144080-31d102af-73cb-4182-a10b-edf420517b08.png)

i was able to successfully call endpoints **/gcdump** and **/trace**. But when I tied to retrieve a dump with **/dump**, I get the following error message: 

```
Problem launching createdump (may not have execute permissions): execve(./createdump) FAILED No such file or directory (2)\n
```

```json
{
  "Timestamp": "2022-11-27T15:26:35.5367849Z",
  "EventId": 1,
  "LogLevel": "Error",
  "Category": "Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController",
  "Message": "Request failed.",
  "Exception": "Microsoft.Diagnostics.NETCore.Client.ServerErrorException: Problem launching createdump (may not have execute permissions): execve(./createdump) FAILED No such file or directory (2)     at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.ValidateResponseMessage(IpcMessage responseMessage, String operationName, ValidateResponseOptions options)    at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.WriteDumpAsync(DumpType dumpType, String dumpPath, WriteDumpFlags flags, CancellationToken token)    at Microsoft.Diagnostics.Monitoring.WebApi.DumpService.DumpAsync(IEndpointInfo endpointInfo, DumpType mode, CancellationToken token)    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.\u003C\u003Ec__DisplayClass16_0.\u003C\u003CCaptureDump\u003Eb__0\u003Ed.MoveNext() --- End of stack trace from previous location ---    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.\u003C\u003Ec__DisplayClass33_0.\u003C\u003CInvokeForProcess\u003Eb__0\u003Ed.MoveNext() --- End of stack trace from previous location ---    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.\u003C\u003Ec__DisplayClass35_0\u00601.\u003C\u003CInvokeForProcess\u003Eb__0\u003Ed.MoveNext() --- End of stack trace from previous location ---    at Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagControllerExtensions.InvokeService[T](ControllerBase controller, Func\u00601 serviceCall, ILogger logger)",
  "State": {
    "Message": "Request failed.",
    "{OriginalFormat}": "Request failed."
  },
  "Scopes": [
    {
      "Message": "SpanId:4620e1ea1b55c0fa, TraceId:1c898095930e9122749828ad62b38e8f, ParentId:0000000000000000",
      "SpanId": "4620e1ea1b55c0fa",
      "TraceId": "1c898095930e9122749828ad62b38e8f",
      "ParentId": "0000000000000000"
    },
    {
      "Message": "ConnectionId:0HMMGH8VQFEG8",
      "ConnectionId": "0HMMGH8VQFEG8"
    },
    {
      "Message": "RequestPath:/dump RequestId:0HMMGH8VQFEG8:00000003",
      "RequestId": "0HMMGH8VQFEG8:00000003",
      "RequestPath": "/dump"
    },
    {
      "Message": "Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureDump (Microsoft.Diagnostics.Monitoring.WebApi)",
      "ActionId": "0fac47bb-2d8d-45ec-be6a-83e1bc007f3b",
      "ActionName": "Microsoft.Diagnostics.Monitoring.WebApi.Controllers.DiagController.CaptureDump (Microsoft.Diagnostics.Monitoring.WebApi)"
    },
    { "Message": "ArtifactType:dump", "ArtifactType": "dump" }
  ]
}
```

### Configuration

kubernetes deployment

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      restartPolicy: Always
      containers:
        - name: app1
          image: mcr.microsoft.com/dotnet/samples:aspnetapp
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: DOTNET_DiagnosticPorts
              value: /diag/port.sock
          volumeMounts:
            - mountPath: /diag
              name: diagvol
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
        - name: app2
          image: mcr.microsoft.com/dotnet/samples:aspnetapp
          imagePullPolicy: Always
          env:
            - name: ASPNETCORE_URLS
              value: http://+:81
            - name: DOTNET_DiagnosticPorts
              value: /diag/port.sock
          volumeMounts:
            - mountPath: /diag
              name: diagvol
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
        - name: monitor
          image: mcr.microsoft.com/dotnet/monitor:6
          # DO NOT use the --no-auth argument for deployments in production; this argument is used for demonstration
          # purposes only in this example. Please continue reading after this example for further details.
          args: ["--no-auth"]
          imagePullPolicy: Always
          env:
            - name: DotnetMonitor_Egress__FileSystem__monitorFile__directoryPath
              value: "/artifacts"
            - name: DotnetMonitor_Egress__FileSystem__monitorFile__intermediateDirectoryPath
              value: "/intermediateArtifacts"
            - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
              value: Listen
            - name: DOTNETMONITOR_DiagnosticPort__EndpointName
              value: /diag/port.sock
            - name: DOTNETMONITOR_Storage__DumpTempFolder
              value: /diag/dumps
            # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
            # demonstration purposes only in this example. Please continue reading after this example for further details.
            - name: DOTNETMONITOR_Urls
              value: http://localhost:52323
          volumeMounts:
            - mountPath: /diag
              name: diagvol
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: diagvol
          emptyDir: {}

```

The error message is not clear if its a permission error, or simple "file not found"
