### ISSUE TITLE
dotnet monitor in kubernetes cluster when 2 or more replicas

### ISSUE THREAD

**Issue by Iceforestik** [dotnet/dotnet-monitor#3025]
I want to monitor several pods of the same application in kubernetes deployment. It turns out to monitor one pod correctly, and if there are many of them, then how to monitor correctly

single replicas deployment config

```
apiVersion: apps/v1
kind: Deployment 
namespace: test       
spec:
  progressDeadlineSeconds: 600
  replicas: 1 
  template:  
    spec:
      volumes:
      - name: diagnostics
        emptyDir: {}
      containers:
      - env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_DiagnosticPort__EndpointName
          value: /diag/port.sock
        - name: DOTNETMONITOR_Storage__DumpTempFolder
          value: /diag/dumps
        - name: DOTNETMONITOR_Urls
          value: http://localhost:52323           
        image: manager:master
        imagePullPolicy: Always
        name: chart
        ports:
        - containerPort: 10800
          protocol: TCP
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /tmp
            name: diagnostics
      - name: sidecar
        image: dotnet/nightly/monitor
        ports:
        - containerPort: 52325
        args: ["collect","--urls", "http://*:52323", "--metricUrls", "http://*:52325", "--no-auth"]
        volumeMounts:
          - name: diagnostics
            mountPath: /tmp
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: 200m
            memory: 500Mi
```
