### ISSUE TITLE
Problem with getting dotnet-monitor to execute configured actions on trigger

### ISSUE THREAD

**Issue by stfab** [dotnet/dotnet-monitor#3131]
### Description

Hi dotnet-monitor team, I set up dotnet-monitor 6 in a sidecar pattern on Kubernetes for an application I'm surveilling. To get gcdumps automatically without triggering the API, I wanted to add triggers and actions that should execute periodically. However, I was not able to get a trigger to execute during a PoC.

I was following the examples on the configuration documentation and set up a simple trigger that should execute if the CPU threshold exceeds a limit. The following logs are all I can see on my sidecar. Now, I'm not sure if the trigger is even firing as nothing happens.

![grafik](https://user-images.githubusercontent.com/33486032/207920402-b83881d9-e24e-473f-9f4f-c9d209a330ca.png)

### Configuration

I have one sample application that is almost the same as the regular ASP.NET sample app for .NET 6 from Microsoft with the following environment variables

```
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/port.sock
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        - mountPath: /dumps
          name: dumpsvol
```

Dotnet-monitor runs as sidecar alongside it with a shared volume "/diag" for communication and a persistent volume claim "/dumps" to save application dumps and egress data persistently.

```
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:6
        imagePullPolicy: Always
        args: ["--no-auth", "--urls", "http://*:52323"]
        ports:
        - containerPort: 52323
        env:
        - name: DotnetMonitor_DiagnosticPort__ConnectionMode
          value: 'Listen'
        - name: DotnetMonitor_DiagnosticPort__EndpointName
          value: /diag/port.sock
        - name: DotnetMonitor_Storage__DumpTempFolder
          value: /dumps
        - name: DotnetMonitor_Logging__Console__FormatterName
          value: simple
        volumeMounts:
        - mountPath: "/diag"
          name: diagvol
        - mountPath: /dumps
          name: dumpsvol
        - mountPath: /etc/dotnet-monitor
          name: dm-config
      volumes:        
      - name: dumpsvol
        persistentVolumeClaim:
          claimName: diagvol-pv-claim
      - name: diagvol
        emptyDir: {}
      - name: dm-config
        configMap:
          name: dotnet-monitor-triggers
```

The following is my dotnet-monitor configuration. As you can see I'm trying to use the /dumps folder for egressing and use a simple rule that should trigger if my CPU usage exceeds 1 to collect a gcdump and traces. I've been trying slight adjustment and other actions like CollectDump without success.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-monitor-triggers
data:
  settings.json: |-
    {
        "Egress": {
            "FileSystem": {
                "monitorFile": {
                    "directoryPath": "/dumps"
                }
            }
        },
        "CollectionRules": {
            "HighCpuRule": {
                "Trigger": {
                    "Type": "EventCounter",
                    "Settings": {
                        "ProviderName": "System.Runtime",
                        "CounterName": "cpu-usage",
                        "GreaterThan": 1,
                        "SlidingWindowDuration": "00:01:00"
                    }
                },
                "Actions": [
                    {
                        "Type": "CollectGCDump",
                        "Settings": {
                            "Egress": "monitorFile"
                        }
                    },
                    {
                        "Type": "CollectTrace",
                        "Settings": {
                            "Profile": "Cpu",
                            "Duration": "00:01:00",
                            "Egress": "monitorFile"
                        }
                    }
                ]
            }
        }
    }
```

### Regression?

So far I haven't been able to get a trigger/action to save something once. The API runs fine if loaded manually. I can get gcdumps, traces and so on. If I trigger the dump API it saves a minidump to /dumps as expected.

I hope you can help me here as I'm not sure if it's a bug or something I've overlooked. Many thanks.
