### ISSUE TITLE
dotnet monitor not working alongside hardened kubernetes container

### ISSUE THREAD

**Issue by Krishnadas-KP** [dotnet/dotnet-monitor#4018]
### Description

I am trying to use dotnet monitor 7 as a diagnostics sidecar alongside a sample kubernetes container. Everything works fine when the kubernetes container is running as root. Both Listen and Connect modes work in this state. However, my use case is that the application container will be running as non root and due to the PodSecurityContext, dotnet monitor also needs to run as non root.

As per https://github.com/dotnet/dotnet-docker/issues/3368, this is a supported scenario.

However, I am unable to get this working when app container is running non root.

As per the above github issue, if both containers are running the same user, it should be able to communicate. But this is not working. I have tried to make both containers run user 405 and user 1000 and have the same effect.

### Configuration

The deployment manifest is as below

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      restartPolicy: Always
      containers:
      - name: app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: "/diag/dotnet-monitor.sock"
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 32Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 100
      - name: sidecar
        image: mcr.microsoft.com/dotnet/monitor
        args: [ "collect", "--no-auth" ]
        ports:
        - containerPort: 52323
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        - name: DOTNETMONITOR_Urls
          value: http://localhost:52323
        - name: DOTNETMONITOR_Metrics__Endpoints
          value: http://+:52325
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 100
      volumes:
      - name: diagvol
        emptyDir: {}
```
