### ISSUE TITLE
Staging shared libraries before startup for startup hooks usage

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#4245]
For listen mode with nosuspend or connect mode, we'll need to have the user specify the path if the startup hook truly needs to be available at managed code startup. Because the target application will likely be executing managed code without waiting for .NET Monitor to instruct it to continue, any libraries that are required to exist at startup must be staged in an accessible location for the target process starts. This is problematic for process namespace separated environments such as Docker and Kubernetes where the target application does not have access to the file system of the .NET Monitor image.

To support these scenarios, the .NET Monitor tool should have a mode that can be used to stage the shared libraries BEFORE the target application container is started. This is typically done as an init container in Kubernetes. An example of how this may be used in a deployment is:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-diag
        image: mcr.microsoft.com/dotnet/nightly/monitor:8.0.0-preview.3
        args: [ "init-shared-path" ]
        env:
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      containers:
      - name: app
        #image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-monitor.sock,nosuspend
        - name: DOTNET_STARTUP_HOOKS
          value: /diag/libs/8.0.0-preview.3.23180.9/any/net6.0/Microsoft.Diagnostics.Monitoring.StartupHook.dll
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      - name: monitor
        image: mcr.microsoft.com/dotnet/nightly/monitor:8.0.0-preview.3
        args: [ "collect", "--urls", "http://localhost:52323", "--metricUrls", "http://+:52325", "--no-auth" ]
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        - name: DotnetMonitor_Experimental_Feature_Exceptions
          value: 'true'
        - name: DOTNETMONITOR_InProcessFeatures__Enabled
          value: 'true'
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      volumes:
      - name: diagvol
        emptyDir: {}
```
