### ISSUE TITLE
Capture dump from root container using non-root .NET Monitor doesn't work

### ISSUE THREAD

**Issue by jander-msft** [dotnet/dotnet-monitor#4427]
Use the following example where the target application is running as root and the .NET Monitor container is running as non-root:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-exampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exampleapp
  template:
    metadata:
      labels:
        app: exampleapp
    spec:
      restartPolicy: Always
      containers:
      - name: app
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:80
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-monitor.sock
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      - name: monitor
        image: mcr.microsoft.com/dotnet/nightly/monitor:8.0.0-preview.4
        args: [ "collect", "--urls", "http://localhost:52323", "--metricUrls", "http://+:52325", "--no-auth" ]
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      volumes:
      - name: diagvol
        emptyDir: {}
```

Attempting to collect a dump from the target application will fail with an error message such as:

```
Access to the path '/diag/dumps/510aa00b-cfe1-4207-b965-90805b922b59_1' is denied.
```

The issue is that the dump is written by the runtime with root read-write permissions but .NET Monitor cannot read it because the 8.0 images run as non-root:

```bash
ls -la /diag/dumps/

drwxr-xr-x    2 64198    64198         4096 May 16 17:51 .
drwxrwxrwx    3 root     root          4096 May 16 17:43 ..
-rw-------    1 root     root     127311872 May 16 17:51 510aa00b-cfe1-4207-b965-90805b922b59_1
```

The only current workaround is to have the .NET Monitor container run as root:

```diff
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:8.0.0-preview.4
        args: [ "collect", "--urls", "http://localhost:52323", "--metricUrls", "http://+:52325", "--no-auth" ]
        imagePullPolicy: Always
+       securityContext:
+         runAsUser: 0
```
