### ISSUE TITLE
Missing Kestrel metrics configuration

### ISSUE THREAD

**Issue by webbsk** [dotnet/dotnet-monitor#464]
### Documentation Request

 

The existing Kestrel documentation is just left as a TODO: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#kestrel-configuration. I've been waiting a few weeks and there doesn't seem to be any movement on completing this section. Is there an ETA on this or can I help get this effort started? I am looking to replace an external in-proc metrics library with this one but I require the Kestrel metrics to be available (and they aren't enabled by default).

**Comment by webbsk** [comment]
Specifically, I am looking to find out how to enable Kestrel metrics provider using a ConfigMap rather than using a JSON file. The hierarchical structure with arrays in it doesn't seem to be covered by the existing example which is only for the top tier properties with simple values: https://github.com/dotnet/dotnet-monitor/blob/main/documentation/configuration.md#translating-configuration-between-providers. This documentation gap would also apply to environment variables.

**Comment by jander-msft** [comment]
Are you asking how to configure (using Kubernetes ConfigMap) dotnet-monitor's `/metrics` route to report counters from the following provider? https://docs.microsoft.com/en-us/dotnet/core/diagnostics/available-counters#microsoft-aspnetcore-server-kestrel-counters

**Comment by webbsk** [comment]
Yes, I'm trying to figure out how I would specify the additional providers give that they look like this in json: 
`{
  "$schema": "https://aka.ms/dotnet-monitor-schema",
  "Metrics": {
    "UpdateIntervalSeconds": 10,
    "Enabled": true,
    "IncludeDefaultProviders": true,
    "Providers": [
      {
      "ProviderName": "Microsoft-AspNetCore-Server-Kestrel"
      },
      {
        "ProviderName": "Microsoft-AspNetCore-Http-Connections"
      }
    ]
  }
}`
How can I put the array of providers in with the additional properties in an env variable (so that it could be put in a ConfigMap)?

**Comment by shirhatti** [comment]
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-hello-world-configmap
data:
  Metrics__Enabled: "true"
  Metrics__UpdateIntervalSeconds: 10
  Metrics__IncludeDefaultProviders: "true"
  Metrics__Providers__0__ProviderName: "Microsoft-AspNetCore-Server-Kestrel"
  Metrics__Providers__1__ProviderName: "Microsoft-AspNetCore-Http-Connections"
```
