### ISSUE TITLE
Dotnet-Monitor not exporting metrics with recommended config

### ISSUE THREAD

**Issue by webbsk** [dotnet/dotnet-monitor#665]
Based on the latest update to my kubernetes yaml files (using a config file mount to pick up configurations), I was expecting it to emit metrics on port 52325. Instead, the http response comes back empty. It looks as the the configuration is not being respecting what is being fed to the command line of the pod on startup or it is overwritten by the config map?

**deployment.yaml**
```
...
        volumeMounts:
        - mountPath: /diag
          name: diagnostics
      - name: dotnetmonitor
        args:
        - collect 
        - --diagnostic-port
        - /diag/port
        command:
        - dotnet-monitor
        image: mcr.microsoft.com/dotnet/nightly/monitor:5.0.0-preview.6
        imagePullPolicy: Always        
        ports:
        - containerPort: 52325
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: "0.25"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /diag
          name: diagnostics
        - mountPath: /etc/dotnet-monitor
          name: dotnetconfig-volume
      volumes:
      - name: bigcat-kv-csi-vol
        projected:
          sources:
          - secret:
              name: bigcat-fd-secrets
      - emptyDir: {}
        name: diagnostics
      - name: dotnetconfig-volume
        configMap:
          name: dotnetmonitor-configmap        
```

**dotnetmonitor-configmap.yaml**

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnetmonitor-configmap 
  namespace: {{ .Values.namespace }}
data:
    Metrics__Enabled: "true"
    Metrics__IncludeDefaultProviders: "true"
    Metrics__Providers__0__ProviderName: Microsoft-AspNetCore-Server-Kestrel
    Metrics__Providers__1__ProviderName: Microsoft-AspNetCore-Http-Connections
    Metrics__Providers__2__ProviderName: System-Net-Security
    Metrics__Providers__3__ProviderName: System-Net-Http
    Metrics__UpdateIntervalSeconds: "30"
    Metrics__AllowInsecureChannelForCustomMetrics: "true"
    DotnetMonitor_DefaultProcess__Filters__0__Key: "ProcessName"
    DotnetMonitor_DefaultProcess__Filters__0__Value: "dotnet"
```

When I run a dotnet-monitor show on the pod, I see the following: 
```
/app # dotnet-monitor config show
{
  "urls": "https://localhost:52323",
  "Kestrel": ":NOT PRESENT:",
  "CorsConfiguration": ":NOT PRESENT:",
  "DiagnosticPort": {
    "ConnectionMode": "Connect",
    "EndpointName": null
  },
  "Metrics": {
    "AllowInsecureChannelForCustomMetrics": "true",
    "Enabled": "true",
    "Endpoints": "http://*:52325",
    "IncludeDefaultProviders": "true",
    "MetricCount": "3",
    "Providers": {
      "0": {
        "ProviderName": "Microsoft-AspNetCore-Server-Kestrel"
      },
      "1": {
        "ProviderName": "Microsoft-AspNetCore-Http-Connections"
      },
      "2": {
        "ProviderName": "System-Net-Security"
      },
      "3": {
        "ProviderName": "System-Net-Http"
      }
    },
    "UpdateIntervalSeconds": "30"
  },
  "Storage": {
    "DumpTempFolder": "/tmp/"
  },
  "DefaultProcess": {
    "Filters": {
      "0": {
        "Key": "ProcessId",
        "Value": "1"
      }
    }
  },
  "ApiAuthentication": ":NOT PRESENT:",
  "Egress": ":NOT PRESENT:"
```
