### ISSUE TITLE
dotnet-monitor sidecar throws 400 error and creates a 0 size dump on Blob

### ISSUE THREAD

**Issue by atif-syed** [dotnet/dotnet-monitor#6991]
Problem Description:
I am running AKS cluster with .NET8 applications in pods as root user. We haven't yet migrated to being non-root user. I want to use dotnet-monitor as sidecar to collect the dumps from my applicaiton. 
I am using Azure workload identity and I want to store my application dumps in Azure Blob object storage. My inhouse application is using dotnet version 8.0.201 

First, to test the dotnet-monitor. I deployed the sample app as is and it only required me to add the Security context and I was able to collect dumps and gcdumps from the sample app to local mount and the Azure blob
I am using Workload identity and Azure blob for dump destination. The sample app taken from Github example works and collects dumps and gcdumps after adding the security context as seen in the test-deploy.txt attached with this issue. This test works in my cluster. 

Second, I moved the same config to my .NET8 application i.e. added Env variables and configmap and the sidecar pod, see app-deploy.txt , I get 0 sized dumps and gc dumps with the following error. Please note all other calls work , like /processes etc

dump collection example 

Port Forward

kubectl port-forward pod-name 52323:52323

Open another terminal and run the following

curl -i -v --limit-rate 500K --retry 5 --keepalive-time 600 'http://localhost:52323/dump?pid=1&egressProvider=monitorBlob'

After running the above, I see a dump file in Blob. Sample application dump collection works

When I port forward to my application pod and repeat the same steps. I see a 0 size dump file in Blob and nothing in the local mount. I see the following error

{"resourceLocation":null,"error":{"code":"400","message":"Could not find file '/diag/dumps/c26b3ca1-0f9c-44df-8080-180239aa5834_1'."},"operationId":"f1c61856-c25c-48ec-ad52-73dcc0ca0ce2","createdDateTime":"2024-07-15T12:48:14.1377562Z","status":"Failed","process":{"pid":1,"uid":"f7ea58ae-04d7-4e7d-ba59-6a7dffd4b306","name":"dotnet"},"egressProviderName":"monitorBlob","isStoppable":false,"tags":[]}

sample app : test-deploy.txt
My .net8 application : app-deploy.txt

===============
Sample app
===============

/app #id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)

/app #whoami
root

/app #ls -lt /diag/
total 4
drwxr-sr-x    2 root     root          4096 Jul 15 13:06 dumps
srwxr-xr-x    1 root     root             0 Jul 11 21:49 port.sock

/app #dotnet --info

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0
  RID:          linux-musl-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

==============================
  Application deploy
==============================

/app/publish# id
uid=0(root) gid=0(root) groups=0(root)

/app/publish# whoami
root

ls -lt /diag
total 4
drwxr-sr-x 2 root root 4096 Jul 15 13:54 dumps
srwxr-xr-x 1 root root    0 Jul 15 13:47 port.sock

/app/publish# dotnet --info

Host:
  Version:      8.0.7
  Architecture: x64
  Commit:       2aade6beb0
  RID:          linux-x64

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

/app/publish# dotnet --list-runtimes
Microsoft.AspNetCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 8.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
[app-deploy.txt](https://github.com/user-attachments/files/16237177/app-deploy.txt)
[test-deploy.txt](https://github.com/user-attachments/files/16237178/test-deploy.txt)

**Comment by atif-syed** [comment]
[app-deploy.txt](https://github.com/user-attachments/files/16241007/app-deploy.txt)
Uploading app-deploy.txt as the previous one was empty

**Comment by atif-syed** [comment]
Sample app deploy , the one that works and takes dump in my kubernetes env


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: akstest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akstest
  template:
    metadata:
      labels:
        app: akstest
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: redacted-svcacct # SA with Workload identity
      restartPolicy: Always
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false      
        fsGroup: 0 # Default APP_ID for the aspnetapp image
      containers:
      - name: publishedapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: DOTNET_DiagnosticPorts
          value: /diag/port.sock
        - name: DotnetMonitor_Storage__DefaultSharedPath
          value: "/diag"
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:8
        args: [ "collect", "--no-auth" ]
        imagePullPolicy: Always
        env:
        - name: DotnetMonitor_DiagnosticPort__ConnectionMode
          value: 'Listen'
        - name: DotnetMonitor_DiagnosticPort__EndpointName
          value: /diag/port.sock
        # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
        # demonstration purposes only in this example. Please continue reading after this example for further details.
        - name: DotnetMonitor_Urls
          value: 'http://localhost:52323'
        - name: DotnetMonitor_Storage__DumpTempFolder
          value: /diag/dumps
        - name: DotnetMonitor_Storage__DefaultSharedPath
          value: "/diag"
        - name: DotnetMonitor_Logging__Console__FormatterName
          value: simple
        - name: AZURE_CLIENT_ID
          value: redacted
        - name: AZURE_TENANT_ID
          value: redacted
        - name: AZURE_AUTHORITY_HOST 
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        - mountPath: /etc/dotnet-monitor
          name: dotnet-monitor-config
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 512Mi
      volumes:
      - name: diagvol
        emptyDir: {}
      - name: dotnet-monitor-config
        projected:
          defaultMode: 400
          sources:
            - configMap:
                name: dotnet-monitor-egress
                optional: false

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-monitor-egress
data:
  Storage__DefaultSharedPath: "/diag"
  Storage__DumpTempFolder: "/diag/dumps/"
  Egress__FileSystem__monitorFile__directoryPath: /diag
  Egress__AzureBlobStorage__monitorBlob__accountUri: "redacted-account-uri"
  Egress__AzureBlobStorage__monitorBlob__containerName: "dumps"
  Egress__AzureBlobStorage__monitorBlob__blobPrefix: "artifacts"
  Egress__AzureBlobStorage__monitorBlob__UseWorkloadIdentityFromEnvironment: "true"
```

**Comment by atif-syed** [comment]
My in house application with dotnet-monitor sidecar , the one that throws error code 400 and creates 0 bite size dumps in Blob. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "243"
    meta.helm.sh/release-name: app-umbrella
    meta.helm.sh/release-namespace: develop-app
  labels:
    app.kubernetes.io/managed-by: Helm
    name: env-app
  name: env-app
  namespace: develop-app
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: env-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        azure.workload.identity/use: "true"
      name: env-app
    spec:
      containers:
      - args:
        - collect
        - --no-auth
        env:
        - name: DotnetMonitor_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DotnetMonitor_DiagnosticPort__EndpointName
          value: /diag/port.sock
        - name: DotnetMonitor_Urls
          value: http://localhost:52323
        - name: DotnetMonitor_Storage__DefaultSharedPath
          value: /diag
        - name: DotnetMonitor_Storage__DumpTempFolder
          value: /diag/dumps
        - name: DotnetMonitor_Logging__Console__FormatterName
          value: simple
        - name: AZURE_CLIENT_ID
          value: redacted
        - name: AZURE_TENANT_ID
          value: redacted
        - name: AZURE_AUTHORITY_HOST
        image: mcr.microsoft.com/dotnet/monitor:8
        imagePullPolicy: Always
        name: env-app-monitor
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 32Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        - mountPath: /etc/dotnet-monitor
          name: dotnet-monitor-config
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: redacted
        - name: app_ENVIRONMENT
          value: redacted
        - name: app_INSTANCEID
          value: redacted
        - name: app_APPNAME
          value: app
        - name: app_APPTYPE
          value: WEB
        - name: ASPNETCORE_URLS
          value: http://+:8080
        - name: DOTNET_DiagnosticPorts
          value: /diag/port.sock
        - name: DotnetMonitor_Storage__DefaultSharedPath
          value: /diag
        - name: DotnetMonitor_Storage__DumpTempFolder
          value: /diag/dumps
        image: redacted/custom-image
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            httpHeaders:
            - name: Host
              value: ""
            path: /healthz
            port: 443
            scheme: HTTPS
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        name: env-app
        ports:
        - containerPort: 443
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Host
              value: ""
            path: /ready
            port: 443
            scheme: HTTPS
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "2"
            memory: 2560Mi
          requests:
            cpu: 250m
            memory: 2Gi
        startupProbe:
          failureThreshold: 40
          httpGet:
            httpHeaders:
            - name: Host
              value: ""
            path: /health/startup
            port: 443
            scheme: HTTPS
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      dnsPolicy: ClusterFirst
      nodeSelector:
        app.target: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 0
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      serviceAccount: app-svcacct
      serviceAccountName: app-svcacct
      terminationGracePeriodSeconds: 60
      volumes:
      - name: diagvol
      - name: dotnet-monitor-config
        projected:
          defaultMode: 400
          sources:
          - configMap:
              name: dotnet-monitor-egress
              optional: false

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dotnet-monitor-egress
data:
  Storage__DefaultSharedPath: "/diag"
  Storage__DumpTempFolder: "/diag/dumps/"
  Egress__FileSystem__monitorFile__directoryPath: /diag
  Egress__AzureBlobStorage__monitorBlob__accountUri: "redacted-account-uri"
  Egress__AzureBlobStorage__monitorBlob__containerName: "dumps"
  Egress__AzureBlobStorage__monitorBlob__blobPrefix: "artifacts"
  Egress__AzureBlobStorage__monitorBlob__UseWorkloadIdentityFromEnvironment: "true"
```
