### ISSUE TITLE
Publishing to BAR/Maestro will no longer support tokens

### ISSUE THREAD

**Issue by premun** [dotnet/dotnet-monitor#7079]
I noticed that you're still using `$(MaestroAccessToken)` when publishing internal builds in https://github.com/dotnet/dotnet-monitor/blob/9946e77b314d52803dd900f5d2e58193cb4dbcc2/eng/pipelines/dotnet-monitor-release.yml#L65-L81.

This token is getting deprecated in favour of using a secretless auth via a service connection.
You will need to change how you do this or your internal builds will break at the end of the month.
The change is not complicated and goes as follows:

Where your pipeline has something like this:
```yaml
- task: PowerShell@2
  displayName: Get Release Version
  inputs:
    filePath: $(Build.SourcesDirectory)/eng/release/Scripts/GetReleaseVersion.ps1
    arguments: >-
      -BarId $(BarId)
      -MaestroToken $(MaestroAccessToken)
      -TaskVariableName 'ReleaseVersion'
```

it will need to change to something like this:

```yaml
- task: AzureCLI@2
  displayName: Get Release Version
  inputs:
    azureSubscription: "Darc: Maestro Production"
    scriptLocation: scriptPath
    scriptPath: $(Build.SourcesDirectory)/eng/release/Scripts/GetReleaseVersion.ps1
    arguments: >
      -BarId $(BarId)
      -TaskVariableName 'ReleaseVersion'
```

The differences between the snippets above are:
-	AzureCLI@2 task is used
-	The “Darc: Maestro Production” service connection is used.
Your pipeline will need to be approved to use this connection (reach out to First Responders).
-	The `$(MaestroAccessToken)` secret is removed
