### ISSUE TITLE
S3Storage EgressExtension cant load AWS token from the service account mounted in a EKS POD

### ISSUE THREAD

**Issue by miguepintor** [dotnet/dotnet-monitor#7201]
# Description

Given an EKS cluster v 1.29 with the EKS Pod Identity Agent installed and an OIDC identity provider created.

1. Create a K8s SA linked to an AWS IAM Role thru IRSA or EKS Pod Identity
2. Spawn a pod with a carside container like this:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - name: app
    image: my-dotnet-app:latest
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
    env:
    - name: DOTNET_DiagnosticPorts
      value: /diag/dotnet-monitor.sock
    volumeMounts:
    - mountPath: /diag
      name: diag-vol
  - name: monitor
    image: mcr.microsoft.com/dotnet/monitor:8
    args: [ "collect", "--no-auth" ]
    imagePullPolicy: Always
    env:
     - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
       value: Listen
     - name: DOTNETMONITOR_Storage__DefaultSharedPath
       value: /diag
     - name: DOTNETMONITOR_Urls
       value: http://localhost:52323
     - name: DOTNETMONITOR_Metrics__Endpoints
       value: http://+:52325
     - name: DOTNETMONITOR_Egress__S3Storage__dump__bucketName
       value: my-bucket
     - name: DOTNETMONITOR_Egress__S3Storage__dump__regionName
       value: eu-west-1
    volumeMounts:
    - mountPath: /diag
      name: diag-vol
    resources:
      requests:
        cpu: 500m
        memory: 500Mi
  volumes:
  - name: diag-vol
    emptyDir: {}
  serviceAccountName: my-sa
```
3. Port forward the monitor pod port to your local machine
```bash
kubectl port-forward pod/test 52323:52323
```
4. Then when you try to upload a dump to the S3 bucket
```bash
curl -i "http://localhost:52323/dump?egressProvider=dump"
```
The dontet-monitor throws the following error;
`
{"Timestamp":"2024-08-25T17:50:51.9854761Z","EventId":91,"LogLevel":"Information","Category":"Microsoft.Diagnostics.Tools.Monitor.Egress.EgressExtension","Message":"Extension process 46 wrote output: {\u0022Succeeded\u0022:false,\u0022FailureMessage\u0022:\u0022Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.\u0022,\u0022ArtifactPath\u0022:null}","State":{"Message":"Extension process 46 wrote output: {\u0022Succeeded\u0022:false,\u0022FailureMessage\u0022:\u0022Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.\u0022,\u0022ArtifactPath\u0022:null}","pid":46,"message":"{\u0022Succeeded\u0022:false,\u0022FailureMessage\u0022:\u0022Assembly AWSSDK.SecurityToken could not be found or loaded. This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.\u0022,\u0022ArtifactPath\u0022:null}","{OriginalFormat}":"Extension process {pid} wrote output: {message}"},"Scopes":[{"Message":"ArtifactType:dump ArtifactSource_ProcessId:1 ArtifactSource_RuntimeInstanceCookie:694f2cff7a5745e48b84ed75f3900ca3","ArtifactType":"dump","ArtifactSource_ProcessId":"1","ArtifactSource_RuntimeInstanceCookie":"694f2cff7a5745e48b84ed75f3900ca3"}]}
`

:warning: Note:
The exact same SA works like a charm when mounted in another pod. e.g. in a pod with an aws-cli container:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: dev-pod
spec:
  containers:
    - name: aws-cli
      image: amazon/aws-cli:latest
      command: ['sleep', '36000']
  restartPolicy: Never
  serviceAccountName: my-sa
```

## Expected
Dotnet-monitor, thru AWSDK should be able to retrieve the mounted token.
Supposedly it reads the following env vars:
 - AWS_REGION
 - AWS_ROLE_ARN
 - AWS_WEB_IDENTITY_TOKEN_FILE
 
 Those env vars are populated automatically when adding a IRSA SA, BUT when adding a SA thru EKS pod identity, others are created (it would be great to have support for those as well). None of them seems to work. Even if you manually populate those env vars.

# Configuration

* Is this related to a specific tool? Egress Providers of Dotnet monitor
* What OS and version, and what distro if applicable? The container used is the official one --> mcr.microsoft.com/dotnet/monitor:8
* What is the architecture (x64, x86, ARM, ARM64)? x64
* Are you running in any particular type of environment? (e.g. Containers, a cloud scenario, app you are trying to target is a different user)  dotnet monitor container deployed in an EKS cluster
