### ISSUE TITLE
Permission denied when access stacks api

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-monitor#7570]
### Description

Exception when trying to access `/stacks` api

```json
{
    "Timestamp": "2024-10-28T14:38:03.2501872Z",
    "EventId": 13,
    "LogLevel": "Error",
    "Category": "Microsoft.AspNetCore.Server.Kestrel",
    "Message": "Connection id \"0HN7NBO88QTAF\", Request id \"0HN7NBO88QTAF:00000004\": An unhandled exception was thrown by the application.",
    "Exception": "System.Net.Sockets.SocketException (13): Permission denied\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.CreateException(SocketError error, Boolean forAsyncThrow)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ConnectAsync(Socket socket, Boolean saeaCancelable)\n   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.ConnectAsync(EndPoint remoteEP)\n   at Microsoft.Diagnostics.Monitoring.WebApi.ProfilerChannel.SendMessage(IEndpointInfo endpointInfo, IProfilerMessage message, CancellationToken token)\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)\n   at Microsoft.Diagnostics.Monitoring.WebApi.ProfilerChannel.SendMessage(IEndpointInfo endpointInfo, IProfilerMessage message, CancellationToken token)\n   at Microsoft.Diagnostics.Tools.Monitor.Stacks.StacksOperation.StacksOperationPipeline.StartAsync(CancellationToken token)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)\n   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)\n   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)\n   at System.Threading.ThreadPoolWorkQueue.Dispatch()\n   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()\n--- End of stack trace from previous location ---\n   at Microsoft.Diagnostics.Monitoring.WebApi.ProfilerChannel.SendMessage(IEndpointInfo endpointInfo, IProfilerMessage message, CancellationToken token)\n   at Microsoft.Diagnostics.Tools.Monitor.Stacks.StacksOperation.StacksOperationPipeline.StartAsync(CancellationToken token)\n   at Microsoft.Diagnostics.Tools.Monitor.PipelineArtifactOperation`1.ExecuteAsync(Stream outputStream, CancellationToken token)\n   at Microsoft.Diagnostics.Tools.Monitor.PipelineArtifactOperation`1.ExecuteAsync(Stream outputStream, CancellationToken token)\n   at Microsoft.Diagnostics.Monitoring.WebApi.OutputStreamResult.<>c__DisplayClass6_0.<<ExecuteResultAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.Diagnostics.Monitoring.WebApi.ActionContextExtensions.<>c__DisplayClass1_0.<<InvokeAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.Diagnostics.Monitoring.WebApi.ExecutionHelper.InvokeAsync[T](Func`2 action, ILogger logger, CancellationToken token)\n   at Microsoft.Diagnostics.Monitoring.WebApi.ActionContextExtensions.InvokeAsync(ActionContext context, Func`2 action, ILogger logger)\n   at Microsoft.Diagnostics.Monitoring.WebApi.OutputStreamResult.ExecuteResultAsync(ActionContext context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)",
    "State": {
        "Message": "Connection id \"0HN7NBO88QTAF\", Request id \"0HN7NBO88QTAF:00000004\":An unhandled exception was thrown by the application.",
        "ConnectionId": "0HN7NBO88QTAF",
        "TraceIdentifier": "0HN7NBO88QTAF:00000004",
        "{OriginalFormat}": "Connection id \"{ConnectionId}\", Request id \"{TraceIdentifier}\":An unhandled exception was thrown by the application."
    },
    "Scopes": [
        {
            "Message": "SpanId:e016103ae5bc26c6, TraceId:5f1ecef52fc863c23cb8fcc837ca21ce, ParentId:0000000000000000",
            "SpanId": "e016103ae5bc26c6",
            "TraceId": "5f1ecef52fc863c23cb8fcc837ca21ce",
            "ParentId": "0000000000000000"
        },
        {
            "Message": "ConnectionId:0HN7NBO88QTAF",
            "ConnectionId": "0HN7NBO88QTAF"
        },
        {
            "Message": "RequestPath:/stacks RequestId:0HN7NBO88QTAF:00000004",
            "RequestId": "0HN7NBO88QTAF:00000004",
            "RequestPath": "/stacks"
        }
    ]
}
```

### Configuration

```yaml
      containers:
      - name: sparktodo-api
        image: weihanli/sparktodo-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "20m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
        env:
        - name: DOTNET_DiagnosticPorts
          value: /diag/dotnet-monitor.sock
        volumeMounts:
        - mountPath: /diag
          name: diagvol
      - name: monitor
        image: mcr.microsoft.com/dotnet/monitor:9.0
        # DO NOT use the --no-auth argument for deployments in production; this argument is used for demonstration
        # purposes only in this example. Please continue reading after this example for further details.
        args: [ "collect", "--no-auth" ]
        imagePullPolicy: Always
        env:
        - name: DOTNETMONITOR_DiagnosticPort__ConnectionMode
          value: Listen
        - name: DOTNETMONITOR_Storage__DefaultSharedPath
          value: /diag
        - name: DotnetMonitor_InProcessFeatures__Enabled
          value: "true"
        # - name: DotnetMonitor_InProcessFeatures__CallStacks__Enabled
        #   value: "true"
        # - name: DotnetMonitor_InProcessFeatures__Exceptions__Enabled
        #   value: "true"
        # ALWAYS use the HTTPS form of the URL for deployments in production; the removal of HTTPS is done for
        # demonstration purposes only in this example. Please continue reading after this example for further details.
        - name: DOTNETMONITOR_Urls
          value: http://localhost:52323
        # The metrics URL is set in the CMD instruction of the image by default. However, this deployment overrides that with the args setting; manually set the URL to the same value using configuration.
        - name: DOTNETMONITOR_Metrics__Endpoints
          value: http://+:52325
        volumeMounts:
        - mountPath: /diag
          name: diagvol
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 250m
            memory: 256Mi
      volumes:
      - name: diagvol
        emptyDir: {}
```

source: https://github.com/WeihanLi/SparkTodo/blob/f75c8f99e52c29edfa5e22f9300720804842b6f6/sparktodo-api-k8s-deploy.yaml#L29
