### ISSUE TITLE
monitor container OOM killed with recommended resource

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/dotnet-monitor#7682]
Hi team, we're using the dotnet-monitor as sidecar in k8s, and we get some OOM from the monitor container, which caused the pod restarts

```yaml
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 32Mi
```

I have some questions about the dotnet-monitor container:

1. Would a dump file be generated when the dotnet-monitor OOM or exited unexpectedly in other scenes?
2. What may cause the dotnet-monitor sidecar OOM? How should we consider a suitable memory resource for our usage? We're using the same config without additional metrics or other things
