### ISSUE TITLE
Metric based triggers interfere with /metrics

### ISSUE THREAD

**Issue by wiktork** [dotnet/dotnet-monitor#923]
Add triggers to configuration. e.g.:
``` yaml
  CollectionRules__ThreadPoolQueuing__Trigger__Type: EventCounter
  CollectionRules__ThreadPoolQueuing__Trigger__Settings__ProviderName: 'System.Runtime'
  CollectionRules__ThreadPoolQueuing__Trigger__Settings__CounterName: 'threadpool-queue-length'
  CollectionRules__ThreadPoolQueuing__Trigger__Settings__GreaterThan: '30.0'
  CollectionRules__ThreadPoolQueuing__Trigger__Settings__SlidingWindowDuration: 00:00:30
  CollectionRules__ThreadPoolQueuing__Actions__0__Type: CollectDump
  CollectionRules__ThreadPoolQueuing__Actions__0__Settings__Egress: monitorBlob
  CollectionRules__ThreadPoolQueuing__Actions__0__Settings__Type: Full
  CollectionRules__HighCPU__Trigger__Type: EventCounter
  CollectionRules__HighCPU__Trigger__Settings__ProviderName: 'System.Runtime'
  CollectionRules__HighCPU__Trigger__Settings__CounterName: 'cpu-usage'
  CollectionRules__HighCPU__Trigger__Settings__GreaterThan: '60.0'
  CollectionRules__HighCPU__Trigger__Settings__SlidingWindowDuration: 00:00:20
  CollectionRules__HighCPU__Actions__0__Type: CollectDump
  CollectionRules__HighCPU__Actions__0__Settings__Egress: monitorBlob
  CollectionRules__HighCPU__Actions__0__Settings__Type: Full
```

Notice that /metrics (from either endpoint) no longer returns System.Runtime providers:

`http://localhost:52325/metrics`

```
# HELP microsoftaspnetcorehosting_requests_per_second Request Rate
# TYPE microsoftaspnetcorehosting_requests_per_second gauge
microsoftaspnetcorehosting_requests_per_second 0 1632868488294
microsoftaspnetcorehosting_requests_per_second 0 1632868498293
microsoftaspnetcorehosting_requests_per_second 0 1632868508294
# HELP microsoftaspnetcorehosting_total_requests Total Requests
# TYPE microsoftaspnetcorehosting_total_requests gauge
microsoftaspnetcorehosting_total_requests 0 1632868478294
microsoftaspnetcorehosting_total_requests 0 1632868488294
microsoftaspnetcorehosting_total_requests 0 1632868498293
# HELP microsoftaspnetcorehosting_current_requests Current Requests
# TYPE microsoftaspnetcorehosting_current_requests gauge
microsoftaspnetcorehosting_current_requests 0 1632868478294
microsoftaspnetcorehosting_current_requests 0 1632868488294
microsoftaspnetcorehosting_current_requests 0 1632868498293
# HELP microsoftaspnetcorehosting_failed_requests Failed Requests
# TYPE microsoftaspnetcorehosting_failed_requests gauge
microsoftaspnetcorehosting_failed_requests 0 1632868478294
microsoftaspnetcorehosting_failed_requests 0 1632868488294
microsoftaspnetcorehosting_failed_requests 0 1632868498293
```
